### PR TITLE
Use github actions instead of travis CI

### PR DESCRIPTION
**Pull request by pieterdavid**
It seems like travis-ci.org isn't building this anymore, and I can't enable the repository with travis-ci.com (somehow the .github.io ones are not found)

### CODE REVIEW

**Comment by swertz** [comment]
The CI job ran and was successful but the website was not updated, I suppose this will only happen upon merging with master? I'm not very familiar with gh actions...

**Comment by pieterdavid** [comment]
It deployed to the wrong branch, and the action that I used doesn't allow to change that... I'll use this one for testing and ping when it works

**Comment by pieterdavid** [comment]
It seems to be working now: deployment was skipped for the PR build, but should be done once merged (I rebased to clean up the failed attempts ;-) )

**Comment by swertz** [comment]
Thanks, let's try!

**Pull request merged**
