### PR TITLE
Use MkDocs

### PR DESCRIPTION
**Pull request by pieterdavid**
A first step towards addressing https://github.com/cp3-llbb/Framework/issues/279

As a patch this doesn't look nice... the first commit empties the repository, the latter add a skeleton MkDocs site (with automatic deployment by travis on every push to master - in practice: merge of a PR), which also includes up-to-date doxygen. I tested the setup [here](https://pieterdavid.github.io/test-mkdocs/), and modifying it is really as easy as committing changes to the markdown source, so it's basically just a wiki with git version control (but more flexibility).

For now the content is just copied from the [Getting Started](https://github.com/cp3-llbb/cp3-llbb.github.io/wiki/CP3-llbb(met):-Getting-Started) wiki page, and the Framework README, but the point is of course that this gives a centralized place for both more high-level and detailed documentation of the different packages (maybe we can make a list and write a few pieces each?)

Two remaining technicalities:
- travis needs an access token (to push to the gh-pages branch). I would generate one for @cp3-llbb-bot but I don't have its password because that was on an old CP3 wiki page... (there is a PR for using a deployment token for this, but it's not merged yet)
- ideally any push to the default Framework branch would trigger a rebuild (to keep doxygen up to date). This can be done using webhooks, but not directly. We could add it to the notifications app.

### CODE REVIEW

**Comment by OlivierBondu** [comment]
well, it looks good to me, but I don't have the bot password either...

should we merge this anyway ?

**Comment by pieterdavid** [comment]
Up to you... what's there now are slightly cleaned up versions of existing documentation (the one that I didn't copy here is SAMADhi, because that's reasonably self-contained on the github wiki for it, but I can add it). It could use more improvements, but the doxygen will still be there, so we can merge and improve piece by piece with PRs.

**Comment by blinkseb** [comment]
I still have the password for the bot :smile:

**Comment by pieterdavid** [comment]
@blinkseb cool :smile: , could you pass it to @delaere , in case he doesn't have it already? I managed to find an auth token for the bot, that should be enough to give Travis push access to this repository.

**Comment by pieterdavid** [comment]
I enabled travis for this repo (after a small fix it runs happily; for deployment we may need to fix the github token because I'm not sure I got the right one), and also copied the [plotIt wiki page](https://github.com/cp3-llbb/plotIt/wiki/List-of-configuration-options) with the last commit.
I think that's most of the documentation we had, except SAMADhi (which has a more complete wiki, so we could also leave that and only put the tutorial version here). Shall we merge this then? Then we can have a look and see what to improve first.

**Comment by delaere** [comment]
If you think that it's ok to go, fine with me .

**Comment by pieterdavid** [comment]
My hacking skills failed... could someone with access to @cp3-llbb-bot 's password replace the `GITHUB_TOKEN` variable in https://travis-ci.org/cp3-llbb/cp3-llbb.github.io/settings with an access token that has the right to push to this repository (it will force-push to the gh-pages branch)?

**Comment by pieterdavid** [comment]
Correction: `GITHUB_TOKEN` (fixed above; only ticking the "public repositories" box when generating one is enough). I should have tried this before merging, but I also enabled travis on my fork, so now there is a preview at https://pieterdavid.github.io/cp3-llbb.github.io/ (most links should be working)

**Comment by pieterdavid** [comment]
Thanks! It worked - in the sense that travis successfully pushed it to gh-pages, now github pages is complaining a bit (it interprets something in the markdown as a variable where it shouldn't, so I have to escape it for both mkdocs and jekyll)

**Comment by pieterdavid** [comment]
A few deployment issues later (FYI: personal organisation sites can only be deployed from the master branch with github pages, so I renamed master to source, and set it to be the default branch), the site is up at https://cp3-llbb.github.io :-)

**Pull request merged**
